language: generic
sudo: required
after_success:
  - pip install virtualenv
  - virtualenv ~/env
  - source ~/env/bin/activate
  - pip install transifex-client
  - sudo echo $'[https://www.transifex.com]\napi_hostname = https://api.transifex.com\nhostname = https://www.transifex.com\npassword ='"$TRANSIFEX_API_TOKEN"$'\nusername = api\n' > ~/.transifexrc
  - if [ "$TRAVIS_BRANCH" = "master" ]; then tx push -s ; fi
