files:
  - source: '/FlymFork/src/main/res/values/[a|s][r|t]r[a|i]*xml'
    translation: /FlymFork/src/main/res/values-%two_letters_code%/%original_file_name%
    translate_attributes: 0
    content_segmentation: 0
